using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Playwright;
using System;
using System.Collections.Generic;
using System.Globalization; 
using System.Linq;
using System.Threading.Tasks;
using TimeKeeperApp.Authorization;
using TimeKeeperApp.Data;
using TimeKeeperApp.Models;

namespace TimeKeeperApp.Pages.Reports
{
    public class GeneratePdfModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IRazorViewRenderer _renderer;
        private readonly UserManager<IdentityUser> _userManager;

        public GeneratePdfModel(ApplicationDbContext db, IRazorViewRenderer renderer, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _renderer = renderer;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string? week, string? user, string? status)
        {
            DateOnly parsed;
            DateOnly? parsedWeek = !string.IsNullOrEmpty(week) &&
                DateOnly.TryParseExact(week, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsed)
                ? parsed
                : (DateOnly?)null;

            var query = _db.TimeEntry.AsQueryable();

            var currentUserId = _userManager.GetUserId(User);

            if (parsedWeek.HasValue)
                query = query.Where(t => t.Week == parsedWeek.Value);

            if (!string.IsNullOrEmpty(user))
                query = query.Where(t => t.UserID == user);

            // A report generated by an intern should only feature their entries;
            // interns do not have access to user filtering, so this should be done in the background
            if (User.IsInRole(Constants.InternRole))
            query = query.Where(t => t.UserID == currentUserId);

            if (!string.IsNullOrEmpty(status))
            {
                if (status == "true")
                {
                    query = query.Where(t => t.ApprovalStatus == true);
                }
                else if (status == "false")
                {
                    query = query.Where(t => t.ApprovalStatus == false);
                }
            }

            var entries = await (from t in query
                                 join u in _db.Users on t.UserID equals u.Id into uj
                                 from u in uj.DefaultIfEmpty()
                                 orderby u.UserName, t.TimeIn
                                 select new
                                 {
                                     UserName = u != null ? u.UserName : t.UserID,
                                     t.Week,
                                     t.TimeIn,
                                     t.TimeOut,
                                     t.HoursWorked
                                 }).ToListAsync();

            var dtoEntries = new List<TimeEntryReportDto>(entries.Count);
            foreach (var e in entries)
            {
                double hours = 0;
                if (e.TimeOut.HasValue)
                {
                    hours = (e.TimeOut.Value - e.TimeIn).TotalHours;
                }

                // per-entry "H:mm" formatted string
                var perHoursFormatted = FormatHours(hours);

                dtoEntries.Add(new TimeEntryReportDto
                {
                    UserName = e.UserName,
                    Week = e.Week,
                    TimeIn = e.TimeIn,
                    TimeOut = e.TimeOut,
                    HoursWorked = perHoursFormatted,
                    HoursDecimal = hours
                });
            }

            // Group totals by username
            var totals = dtoEntries
                .GroupBy(x => x.UserName ?? "")
                .Select(g =>
                {
                    var sum = g.Sum(x => x.HoursDecimal);
                    return new UserWeekTotalDto
                    {
                        UserName = g.Key,
                        TotalHours = sum,
                        TotalHoursFormatted = FormatHours(sum)
                    };
                })
                .OrderBy(t => t.UserName)
                .ToList();

            var model = new ReportViewModel
            {
                Entries = dtoEntries,
                Totals = totals
            };

            // Render the partial to HTML. pass the ReportViewModel (not the raw list)
            var html = await _renderer.RenderViewToStringAsync("/Pages/TimeEntryPages/ReportPartial.cshtml", model);

            // Convert HTML to PDF using Playwright
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = true });
            var page = await browser.NewPageAsync();
            await page.SetContentAsync(html, new PageSetContentOptions { WaitUntil = WaitUntilState.NetworkIdle });
            var pdfBytes = await page.PdfAsync(new PagePdfOptions { Format = "A4", PrintBackground = true });

            var fileName = $"TimeSheet-{(parsedWeek?.ToString("yyyy-MM-dd") ?? "All")}.pdf";
            return File(pdfBytes, "application/pdf", fileName);
        }

        private static string FormatHours(double hours)
        {
            // convert fractional hours to H:mm where H can exceed 24
            var totalMinutes = (int)Math.Round(hours * 60);
            var h = totalMinutes / 60;
            var m = Math.Abs(totalMinutes % 60);
            return $"{h}:{m:00}";
        }
    }
}